name: Build Board Images
on: [push]
jobs:
  build-images:
    strategy:
      matrix:
        board_name:
          #           - bananapim1
          #           - nanopineo2
          #           - nanopineo
          #           - nanopir1
          #           - odroidxu4
          #           - orangepione
          #           - orangepizero
          #           - raspberrypi2
          #           - raspberrypi3
          - raspberrypi4
          #           - raspberrypi
          #           - tinkerboard
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build artifacts
        run: ./docker-build.sh boards
        # run: ./docker-build.sh ${{ matrix.board_name }}
      - name: generate release images
        # run: sudo ./build.sh boards
        run: >
          sudo mkdir -p output/${{ matrix.board_name }}/images &&
          sudo touch output/${{ matrix.board_name }}/images/board.img &&
          sudo touch output/${{ matrix.board_name }}/images//${{ matrix.board_name }}-foo.img &&
          sudo touch output/${{ matrix.board_name }}/images//${{ matrix.board_name }}-foo.xz
